services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libaio1
- docker run --detach --name cb-test -p 8091-8094:8091-8094 -p 11210:11210 nhive/couchbase-test
language: java
jdk:
- oraclejdk8
- openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.embedmongo
  - $HOME/.embedmysql
  - $HOME/.embedpostgresql
  - $HOME/.m2
