before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libaio1
language: java
jdk:
  - oraclejdk8
  - openjdk9
  - openjdk10
cache:
  directories:
  - $HOME/.embedmongo
  - $HOME/.embedmysql
  - $HOME/.embedpostgresql
  - $HOME/.m2
